sudo: false
language: node_js
node_js:
  - "node"
services:
  - mongodb
  - rabbitmq
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - npm run test:ci
cache:
  yarn: true
  directories:
    - packages/amqp/node_modules
    - packages/core/node_modules
    - packages/express/node_modules
    - packages/graphql/node_modules
    - packages/log4js/node_modules
    - packages/mongoose/node_modules
    - packages/typeorm/node_modules
branches:
  only:
    - master
